"""first

Revision ID: 61adb9ddf862
Revises: 
Create Date: 2023-06-22 12:35:10.828589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61adb9ddf862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baked_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bakeries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bakeries')
    op.drop_table('baked_goods')
    # ### end Alembic commands ###
